### ISSUE TITLE
Mention excluding on the badges input

### ISSUE THREAD

**Issue by vansh-codes** [Shobhit-Nagpal/gssoc-stats-gen#5]
![image](https://github.com/user-attachments/assets/23b8e274-7933-4408-b3a3-7fb523d1d135)

We should mention `Exluding postman badge` on the input label `Badges` as it is interpreted wrong by users

**Comment by ShashwatAgrawal20** [comment]
@vansh-codes what does that even mean? are you referring to the placeholder for badges?

**Comment by vansh-codes** [comment]
> @vansh-codes what does that even mean? are you referring to the placeholder for badges?

Placehold or label anywhere it works

**Comment by Shobhit-Nagpal** [comment]
Hey @vansh-codes, thanks for raising the issue. Thought about this, and maybe I could be wrong but I don't see this being an issue currently. If required to change in the future, will do it asap.

Thank you :)
